### ISSUE TITLE
questions about a and theta in unit hydrograph.

### ISSUE THREAD

**Issue by Billcui123** [OuyangWenyu/hydromodel#14]
Appreciate for your work.Here I have some questions. Are the parameters "a and theta" just same as  "n and k"? If not ,how to convert?

**Comment by OuyangWenyu** [comment]
Do you mean parameters of the Nash model (cascade linear reservoirs)? Honestly, I didn't derive these equations by myself, but the equations in the mizuRoute and Nash models are almost the same. You can confirm this by comparing these papers:  http://hydrologie.org/redbooks/a045/045011.pdf    www.geosci-model-dev.net/9/2223/2016/
