### ISSUE TITLE
你好请问，示例文件如何自动生成多个fold

### ISSUE THREAD

**Issue by KmBase** [OuyangWenyu/hydromodel#20]
![image](https://user-images.githubusercontent.com/10486408/224664147-5b575d67-33cc-4a70-801e-3a626da540ad.png)

**Comment by OuyangWenyu** [comment]
你好，你可以试试这个：https://github.com/OuyangWenyu/hydro-model-xaj/blob/05de0cff1143b8496e4d97016b8db7be91180b1a/hydromodel/app/datapreprocess4calibrate.py#L66

**Comment by KmBase** [comment]
好的，感谢大佬回复

**Comment by OuyangWenyu** [comment]
> 好的，感谢大佬回复

哈哈，不是大佬，欢迎指教

**Comment by OuyangWenyu** [comment]
之前的example数据可能有点问题，现在已经修复了，另外，可以尝试自己生成实际使用的数据，https://github.com/OuyangWenyu/hydro-model-xaj#how-to-make-the-sample-data

**Comment by OuyangWenyu** [comment]
已经更新数据接口到新版本了，readme可以查看
