### ISSUE TITLE
这个是我报错的过程

### ISSUE THREAD

**Issue by wangjingyi1999** [OuyangWenyu/hydromodel#21]
Please Check your directory:
ROOT_DIR of the repo:  D:\hydro-model-xaj-master\hydro-model-xaj-master
DATASET_DIR of the repo:  D:\data
Compare evaluation results of different calibrated models in an exp directory
All settings in an exp directory: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "datapostprocess4calibrate.py", line 156, in <module>
    statistics(the_args)
  File "datapostprocess4calibrate.py", line 112, in statistics
    mean_df_test = pd.concat(mean_lst_test, axis=1).T
  File "D:\ProgramData\Anaconda3\envs\xaj\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\xaj\lib\site-packages\pandas\core\reshape\concat.py", line 304, in concat
    sort=sort,
  File "D:\ProgramData\Anaconda3\envs\xaj\lib\site-packages\pandas\core\reshape\concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by OuyangWenyu** [comment]
你好，把的hydro-model-xaj-master文件夹截个图贴一下吧

**Comment by wangjingyi1999** [comment]
> 你好，把的hydro-model-xaj-master文件夹截个图贴一下吧

![1680929111557](https://user-images.githubusercontent.com/115329855/230703576-7873871b-c959-4a32-8ba8-1a9858cf4cec.jpg)

**Comment by OuyangWenyu** [comment]
应该有个结果文件夹 “result” 吧，你可以把率定那一步你怎么执行的贴过来看看

**Comment by OuyangWenyu** [comment]
> > 你好，把的hydro-model-xaj-master文件夹截个图贴一下吧
> 
> ![1680929111557](https://user-images.githubusercontent.com/115329855/230703576-7873871b-c959-4a32-8ba8-1a9858cf4cec.jpg)

应该有个结果文件夹 “result” 吧，你可以把率定那一步你怎么执行的贴过来看看

**Comment by OuyangWenyu** [comment]
应该有个结果文件夹 “result” 吧，你可以把率定那一步你怎么执行的贴过来看看

**Comment by wangjingyi1999** [comment]
> 应该有个结果文件夹 “result” 吧，你可以把率定那一步你怎么执行的贴过来看看

您好，这是我执行的code，它没有报错，但也没有生成结果文件。
![image](https://user-images.githubusercontent.com/115329855/230762169-cb54f25c-eeed-4afd-85f6-4331fd0f9e36.png)

**Comment by OuyangWenyu** [comment]
hydromodel\example\example  这个文件夹你找找

**Comment by OuyangWenyu** [comment]
之前的example数据有点问题，现在可以再试试

**Comment by wangjingyi1999** [comment]
谢谢大神，这次示例文件可以跑通了。

**Comment by Xunannn** [comment]
你好，我也是这一步报了相同的错误，请问怎么修改呢
<img width="392" alt="率定错误" src="https://github.com/OuyangWenyu/hydro-model-xaj/assets/155137206/66ace6e4-b70d-4378-bf58-b31661d55a67">

**Comment by wangjingyi1999** [comment]
> 你好，我也是这一步报了相同的错误，请问怎么修改呢 <img alt="率定错误" width="392" src="https://private-user-images.githubusercontent.com/155137206/293641183-66ace6e4-b70d-4378-bf58-b31661d55a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDAxOTksIm5iZiI6MTcwNDE5OTg5OSwicGF0aCI6Ii8xNTUxMzcyMDYvMjkzNjQxMTgzLTY2YWNlNmU0LWI3MGQtNDM3OC1iZjU4LWIzMTY2MWQ1NWE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMjUxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWM1ZWNlMTcwMGRmMGFmOTAwNTZhYzQyY2QzNzQ3NWYyNDYwYTIzNWJlOTQ4YmU5MGIwNzg4NmZhMDRkOGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RXQJtS7SPTx39xzCdwm7-vRxERSx_0CoOxnyLIZQTTE">

你好，你看一下hydromodel\example\example里有生成结果吗，如果没有，检查一下calibarate_xaj.py程序里的路径是否正确
