### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by yizhih** [OuyangWenyu/hydromodel#22]
用pycharm运行calibrate_xaj.py时提示出现该问题，但是所有包都安装完毕，也没有修改程序。请教是什么原因

**Comment by OuyangWenyu** [comment]
你好，能把报错的完整信息贴一下么

**Comment by yizhih** [comment]
Traceback (most recent call last):
  File "D:\其他\新安江\hydro-model-xaj-master\hydromodel\app\calibrate_xaj.py", line 15, in <module>
    from hydromodel.calibrate.calibrate_sceua import calibrate_by_sceua
  File "D:\其他\新安江\hydro-model-xaj-master\hydromodel\calibrate\calibrate_sceua.py", line 7, in <module>
    from hydromodel.models.gr4j import gr4j
  File "D:\其他\新安江\hydro-model-xaj-master\hydromodel\models\gr4j.py", line 8, in <module>
    from hydromodel.models.xaj import uh_conv
  File "D:\其他\新安江\hydro-model-xaj-master\hydromodel\models\xaj.py", line 886
    return q_sim, es, *w, s, fr, qi, qg
                      ^
SyntaxError: invalid syntax
这个是完整报错

**Comment by OuyangWenyu** [comment]
看一下你代码运行的python环境，像下面这样，贴一下吧：
![2TE0GK}X6 TUC2(IPV@02J](https://user-images.githubusercontent.com/10172837/233919629-6ba71e25-7923-4a5c-967e-c67c99290d35.png)
然后找到其中的python，把python的版本号贴一下。

或者命令行输入：
`Bash
conda activate xaj
conda list
`
# 把完整列表贴一下

**Comment by yizhih** [comment]
![I`_%`N(IRNYB3TVHE)`)F C](https://user-images.githubusercontent.com/49873659/233922928-19eddaa0-2d89-4ccc-8bc6-7d75128f728f.png)
我用的是3.7版本的

**Comment by OuyangWenyu** [comment]
那应该是版本问题，创建一个单独的虚拟环境吧
![image](https://user-images.githubusercontent.com/10172837/233924484-4c4723b8-6180-4611-9319-251c47c71e39.png)
![image](https://user-images.githubusercontent.com/10172837/233924535-14a056c1-acc0-4ec4-bbb7-562ce10634d2.png)
python 3.10的应该不会有问题

**Comment by yizhih** [comment]
好滴，我试试，谢谢大佬！
