### ISSUE TITLE
模型的输入是什么

### ISSUE THREAD

**Issue by iFence** [OuyangWenyu/hydromodel#25]
我看到readme文件中提到模型的数据是一个三维数组[时间，流域，变量]。那这里的变量是指什么，我看到代码中变量应该是降雨和蒸散发数据，对吗。
换句话说，预报模型中，需要降雨数据/蒸散发数据和率定出来的16个变量这三类数据对吗。

**Comment by OuyangWenyu** [comment]
变量的意思是输入或者输出变量，不是指参数，对于新安江模型，输入变量就是降雨和潜在蒸散发，输出变量就是径流。
这块就是准备数据用来率定或者模拟的时候，需要把数据组织成这样一种统一的三维形式，相当于约定好一个数据格式来遵守，后面模型就容易标准化。

**Comment by iFence** [comment]
`"variable": [
        "prcp(mm/day)",
        "pet(mm/day)",
        "streamflow(mm/day)"
    ],`
上面的streamflow是什么，是流量吗，如果是流量，单位不应该是m³/s，m³/day类似这种的单位嘛，为啥是mm/day呢

**Comment by OuyangWenyu** [comment]
因为为了计算的时候不用再转换单位，所以径流统一转换为流域径流深，也就是径流摊到整个流域面积上的数值

**Comment by iFence** [comment]
明白了，谢谢
