### ISSUE TITLE
模型不需要dem数据吗

### ISSUE THREAD

**Issue by iFence** [OuyangWenyu/hydromodel#26]
我发现模型里面没有用到二维数据，比如代表地形的dem数据，代表流域边界的shp数据等。模型中没有用到这些数据吗

**Comment by OuyangWenyu** [comment]
嗯……这个问题其实延伸来看还是比较复杂的，我就简单说好了。第一，实际操作上到底用到shp没有？-- 用到了，计算中需要流域面积，要想知道流域面积，得有shp，要shp，通常都是需要DEM来生成，另外降雨等数据也都是要被处理到流域范围内的，本项目中没有太多讨论这些前处理的事情，为了跑通实例，直接用了美国NCAR的公开数据集CAMELS中的一些处理好的流域的数据。第二，这些数据直接参与模型计算了么？可以说没有，对于集总式模型，流域内的异质性是被系统性地考虑地，并没有完全显式地表达出来。第三，模型不需要充分利用这些信息么？理论上来说是需要的，这也是包括地貌单位线、分单元半分布式模型或者分布式模型研究的一个动机吧。
