### ISSUE TITLE
执行python calibrate_xaj.py的报错

### ISSUE THREAD

**Issue by Wushaox** [OuyangWenyu/hydromodel#29]
你好，请问这个报错是咋回事，执行示例第一步的。
![图片](https://github.com/OuyangWenyu/hydro-model-xaj/assets/52245065/63ec8c42-f055-452b-bb4b-eb3b240f6ec4)

**Comment by Wushaox** [comment]
ok加了引号解决了

**Comment by OuyangWenyu** [comment]
你好，你是跑的这个命令吗：python calibrate_xaj.py --exp example --warmup_length 365 --model {\"name\":\"xaj_mz\",\"source_type\":\"sources\",\"source_book\":\"HF\"} --algorithm {\"name\":\"SCE_UA\",\"random_seed\":1234,\"rep\":5000,\"ngs\":20,\"kstop\":3,\"peps\":0.1,\"pcento\":0.1}

**Comment by Wushaox** [comment]
是的![图片](https://github.com/OuyangWenyu/hydro-model-xaj/assets/52245065/103b028f-458e-4c02-b22b-df1320878e45)

**Comment by OuyangWenyu** [comment]
你试下在windows的终端下面或者cmd下面运行这个命令，注意python calibrate_xaj.py --exp example --warmup_length 365 --model {\"name\":\"xaj_mz\",\"source_type\":\"sources\",\"source_book\":\"HF\"} --algorithm {\"name\":\"SCE_UA\",\"random_seed\":1234,\"rep\":5000,\"ngs\":20,\"kstop\":3,\"peps\":0.1,\"pcento\":0.1} 命令里面那些 "\"都要留着
![image](https://github.com/OuyangWenyu/hydro-model-xaj/assets/10172837/31a3a436-15a1-4913-b57c-47d23e21f2f8)

**Comment by Wushaox** [comment]
还是同一个问题
![图片](https://github.com/OuyangWenyu/hydro-model-xaj/assets/52245065/151e322c-78aa-4a5d-be2b-53b058e05cf3)
![图片](https://github.com/OuyangWenyu/hydro-model-xaj/assets/52245065/3daa8d42-8606-404b-91c7-9ab40134b5d2)
不过我在pycharm里可以运行

**Comment by Wushaox** [comment]
还有我想问一下如果要改成自己的区域，是只需要准备这四个文件就可以吗
![图片](https://github.com/OuyangWenyu/hydro-model-xaj/assets/52245065/2da2058b-b9ec-46c0-8d0f-8c59811d2fe8)

**Comment by OuyangWenyu** [comment]
命令里要有“\”  要不然命令行读不出来"\"后面的字符串；对的 只要把数据改成自己的就行了

**Comment by Wushaox** [comment]
好的，非常感谢
