### ISSUE TITLE
想问一下自带训练数据

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydromodel#32]
作者您好，可以大概给介绍一下代码当中用于训练的数据的构成么？感激不尽！

**Comment by forestbat** [comment]
以本库为例，使用的是Camels数据集，详情见https://gdex.ucar.edu/dataset/camels.html。
主要是txt文件，记录美国2005-2014年673个流域的雨量、流量、墒情等数据。

基于你过往的提交记录来看，你似乎并不了解新安江模型的性质，以及你具体要做什么项目，请谨慎思考。

**Comment by OuyangWenyu** [comment]
你好，率定模型得到一些参数，具体使用就是利用这一套参数去运行

**Comment by KiltAB** [comment]
谢谢，我通过率定模型最终得到的参数是截图的这些么？这个有具体使用的案例么？
![ca71f3e55c4ed8a90ccee03d35a2837](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/cab307e5-de64-41fa-b2ea-6683c66d779d)

**Comment by OuyangWenyu** [comment]
是的，具体使用的话，可以参考下这个：https://github.com/OuyangWenyu/hydro-model-xaj/blob/a2d49aced220df7f1b87a4cc4ee8238e898956c4/test/test_xaj.py#L132  率定能搞定的话 测试更简单

**Comment by KiltAB** [comment]
非常感谢大佬，还有个小问题，就是我刚才截的图，为什么这些流域输出的这些参数会有两组，这两组参数代表什么呢？
![image](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/1c312212-7d35-44c9-ba81-eb0249d595ed)

**Comment by OuyangWenyu** [comment]
第一组是参数归一化的值  第二组是真实值

**Comment by KiltAB** [comment]
所以用模型预测的话，主要是用第二组值就可以对么？

**Comment by OuyangWenyu** [comment]
对的

**Comment by OuyangWenyu** [comment]
已经改进了前后处理数据接口，可以根据新的readme来操作，使用自己的数据
