### ISSUE TITLE
关于时段长的问题，是否只能跑日模？

### ISSUE THREAD

**Issue by Wushaox** [OuyangWenyu/hydromodel#33]
你好，我看示例数据中时段是天为单位的，我想问下如果我想跑3h时段长的数据是否需要修改些内容？我制作输入文件试了下是可以跑通，但是不太确定计算是否可以直接用于小时时段的，参数需要处理下吗？

**Comment by forestbat** [comment]
是的，目前水源划分（xaj.sources方法）里的ki、kg之类系数是按照天来写的，如果要按照小时尺度需要按照此公式调整：
![image](https://github.com/OuyangWenyu/hydro-model-xaj/assets/23413915/4faffa8f-0da0-451c-a761-a255a549bb29)
具体可参考sources5mm方法。

**Comment by OuyangWenyu** [comment]
模型一直都可以运行小时尺度，需要注意参数的范围，还有模型配置部分 使用sources5mm的分水源方法
