### ISSUE TITLE
关于datapostprocess4calibrate.py文件生成率定数据

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydromodel#34]
暂时解决，感谢！

**Comment by KiltAB** [comment]
还是有一些问题，在运行datapostprocess4calibrate.py的时候，一般这种情况该怎么解决呢，求告知
![4b0609d0eafaaa98568d291e6343660](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/16f56c55-8885-4ca0-b191-fc5f4cb31ea2)

**Comment by OuyangWenyu** [comment]
应该是版本的问题 看下hydro-model-xaj下面安装的hydrodataset的版本是多少？

**Comment by KiltAB** [comment]
版本是0.1.7，用pip直接装上的，需要换成0.1.6么？还是？

**Comment by OuyangWenyu** [comment]
具体哪个版本我忘了 这是个bug 不小心改错了  我尽快修复下  如果你能直接改hydro-model-xaj源码去用 你可以直接把read_basin_area 改个名： read_area  回头等我更新了 你再换回来

**Comment by KiltAB** [comment]
这两个函数应该是一个意思是吧，非常感谢，我改一下试试，另外刚开头那两行debug，说是module ‘forge’ has no attribute ‘copy’，这个会有影响么？应该是在import hydrodataset的时候出现的问题

**Comment by KiltAB** [comment]
很抱歉还得再麻烦一下，又出现了新的问题，我看了一下这个路径，里边什么都没有，是因为缺少什么东西么
![4ecc75dcc5b2ef34acf4c58fbde3c47](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/8cfd72af-ec7d-4f1d-93af-520069b27511)

**Comment by OuyangWenyu** [comment]
这个运行一下 这两行代码 https://github.com/OuyangWenyu/hydrodataset/blob/5c0abd6027ab396d00c031a627f06f5b98d290fb/tests/test_camels.py#L35  生成一下nc格式的数据就行了

**Comment by KiltAB** [comment]
非常感谢解答，调试运行成功！但是如果要是换成自己的数据，是不是不太好弄呢，我看camles是hydrodataset里边的，换成自己的数据去率定的话需要修改很多东西

**Comment by OuyangWenyu** [comment]
嗯 需要改一些东西   https://github.com/OuyangWenyu/hydro-model-xaj/blob/master/hydromodel/data/camels_format_data.py  参考下这个吧 自己把数据做成类似camels的形式 然后再写个这种代码 应该还行 不是特别麻烦  我这边后续如果有同学能写一些文档 会更新一下怎么添加自己的数据等说明的

**Comment by KiltAB** [comment]
好嘞好嘞，我研究一下，麻烦大佬了！不胜感激！！！
