### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by chqbb** [OuyangWenyu/hydromodel#35]
你好，我看到您的example中给出的训练集测试集中他们是将4个流域的数据放到一起，并且他们有着相同的时间长度，我现在想要使用自己的数据集进行训练，我的数据是一个流域的多个场次洪水，他们不是连续的时间序列，那么我该如何进行处理

**Comment by OuyangWenyu** [comment]
你好，场次的应该也是ok的，但是改动会比较多一点，我们这边有人弄了，但是代码比较乱，所以具体的还需要自己改改。大体上就是你可以把现在的长序列当成一场，然后如果是多场的话，就需要加点循环之类的，具体在哪加就需要debug程序看看了

**Comment by OuyangWenyu** [comment]
还有一个办法是每场之前留够比如一个月的预热期，然后就可以把这些数据直接拼接起来，这样是最简单的
