### ISSUE TITLE
关于模型使用

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydromodel#36]
针对率定后模型使用问题，是通过函数test_xaj来实现的，但是在用这个函数的时候有个小问题请教一下，就是关于函数xaj的参数p_and_e，理论上应该是一个三维的数组，包含[time, basin]，time毫无疑问是时间，然后我不太了解的是：这个p_and_e算是输入数据么？新安江的输入数据不应该是‘降雨’和‘蒸发’么？basin这个值具体代表什么呢？
![3fc280f65d65cb6604a7734d02dd786](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/1be78a5b-5a21-4f58-8ed1-9be3f966f5f7)
![dcf128e1b300ca2e0627f755aa46380](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/852a874d-7979-409d-a6a3-7b2534f07316)

**Comment by OuyangWenyu** [comment]
p_and_e就是降雨和潜在蒸散发  basin就是指流域
