### ISSUE TITLE
关于camels_cc

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydromodel#37]
在使用自己的数据训练过程中，都需要那些文件呢，我看camels_format_data中gauge_id_file，它读取的是gage_points.csv，这个文件对应camels_us数据中的哪一个文件呢？gage_points.csv具体是什么呢？有什么行列排版要求么？望解答，感谢！
![7f16e556aa827e5b1c11a649096b287](https://github.com/OuyangWenyu/hydro-model-xaj/assets/99948662/314c358d-14a8-48a5-99af-6a8083cb9289)

**Comment by OuyangWenyu** [comment]
已经改进了前后处理数据接口，可以根据新的readme来操作，使用自己的数据
