### ISSUE TITLE
关于初始值

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydromodel#38]
我想问一下关于数据camels_us用于新安江率定的参数初始值是多少？从哪个文件看呢

**Comment by OuyangWenyu** [comment]
初始值应该是随机设置的 只是给定了一个取值范围 取值范围在这里：https://github.com/OuyangWenyu/hydro-model-xaj/blob/a2d49aced220df7f1b87a4cc4ee8238e898956c4/hydromodel/models/model_config.py#L14
