### ISSUE TITLE
率定参数时索引超出范围

### ISSUE THREAD

**Issue by shituxingzhehhl** [OuyangWenyu/hydromodel#49]
### Environment Information

-   hydromodel version:0.2.4
-   Python version:3.10
-   Operating System:

### Description

运行calibrate_xaj.py时，无论如何修改时间长度总是报错IndexError，调试后发现是xaj.py第880行索引j超出范围，但Traceback中错误信息显示为axis 0

### What I Did

将xaj.py中j范围改为range(len(l)-1)后此bug不出现，变为RMSE计算中出现空值

**Comment by shituxingzhehhl** [comment]
![微信截图](https://github.com/user-attachments/assets/aca6c405-6742-44b7-a9c3-1981a3bc9e59)

**Comment by OuyangWenyu** [comment]
你好，感谢告知bug，我这两天有空了看一下哪个环节出问题了，最近我们还率定了几十个流域，没遇到过这个问题，我查查，感谢！

**Comment by OuyangWenyu** [comment]
![image](https://github.com/user-attachments/assets/950a4951-b849-42fd-b987-2727e9ce1178)
我这边测试确实没出现这个bug，就是目前这个代码只支持单个流域的计算，多个流域一起计算的话，xaj这套（CSL地表汇流）没充分测试，可能是这方面的问题；另外就是请更新一下版本，我们24/08/15会更新一个版本

**Comment by OuyangWenyu** [comment]
知道原因了，之前0.2.5版本把单位线长度当作参数了，现在我把它放到model的设置项了，默认是15个时段，设置的话可以像这样：https://github.com/OuyangWenyu/hydromodel/blob/fc46262be46e855745e08c1f74220acc163794bc/scripts/calibrate_xaj.py#L216   现在应该没有这个bug了
