### ISSUE TITLE
differentiable version of XAJ的代码路径

### ISSUE THREAD

**Issue by Myfootnotsmelly** [OuyangWenyu/hydromodel#50]
你好，对differentiable version of XAJ的实现十分感兴趣，但在hydromodel/models/路径下的文件中没有找到相关代码，可以提供下相关访问方式吗

**Comment by OuyangWenyu** [comment]
你好，可以关注下我们的torchhydro工具，暂时没有细致文档，后续随着相关论文完善，会不断更新
